import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ShieldCheck } from "lucide-react";

type Props = {
  seo: {
    alt: string;
    sizes: string[];
    tags: string[];
  };
};

export function SeoTipsCard({ seo }: Props) {
  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base">SEO Tips</CardTitle>
      </CardHeader>

      <CardContent className="space-y-3">
        <div className="text-xs text-muted-foreground">Suggested alt text</div>
        <div className="rounded-lg border p-3 text-sm">{seo.alt}</div>

        <div className="text-xs text-muted-foreground">Best sizes for srcset</div>
        <div className="flex flex-wrap gap-2">
          {seo.sizes.map((s) => (
            <Badge key={s} variant="outline">
              {s}
            </Badge>
          ))}
        </div>

        <div className="text-xs text-muted-foreground">Suggested tags</div>
        <div className="flex flex-wrap gap-2">
          {seo.tags.map((t) => (
            <Badge key={t} variant="secondary">
              {t}
            </Badge>
          ))}
        </div>

        <div className="flex items-center gap-2 text-xs text-muted-foreground pt-1">
          <ShieldCheck className="h-4 w-4" />
          Recommendations are generated by ML + heuristics
        </div>
      </CardContent>
    </Card>
  );
}
